name: Publish Docker image
on:
  push:

jobs:
  push_to_registry:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          ref: ${{ github.ref_name }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push ModularAssistentForDiscordServer
        uses: docker/build-push-action@v3
        with:
          file: ./ModularAssistentForDiscordServer/Dockerfile
          push: true
          tags: |
            ghcr.io/plerx2493/mads:latest
            ghcr.io/plerx2493/mads:${{ github.sha }}
          build-args: |
            "BUILD_VER=${{ github.sha }}"
            
      - name: Build and Push QuartzDB
        uses: docker/build-push-action@v3
        with:
          file: ./QuartzNetDocker/Dockerfile
          push: true
          tags: |
            ghcr.io/plerx2493/quartz-db-mysql:latest
            ghcr.io/plerx2493/quartz-db-mysql:${{ github.sha }}
          build-args: |
            "BUILD_VER=${{ github.sha }}"